chgflownet:
 _target_: pl_modules.CHGFlownet.CHGFlownet
 max_blocks: 3
 device: 'cuda:0'
 lr: 0.0001
 lr_Z: 0.1
 scheduler_milestone: 5000
 gamma_scheduler: 1.0
 initlogZ: 0.0
 n_iterations: 10000
 alpha_schedule: 1.0
 alpha: 1.0
 clampmin: -10.0
 clampmax: 10.0
 batch_size: 32
 save_freq: 50
 use_pretrain: False
 phidden_dim: 32
 pretrain_model_name: alignn
 proxy_model: M3GNet-MP-2018.6.1-Eform
 with_stop: True
 min_stop: 3
 policy_nn: graph
 ele_set: battery
 #Fraction cooridnate min and max
 frlocmin: 0.0
 frlocmax: 1.0
 #Min and max of mean and std of normal distribution of lattice length
 llocmin: 4
 llocmax: 10
 lsclmin: 1
 lsclmax: 2
 #Min and max of cov matrix of multivariate normal distribution of fraction coordinate
 frcovmin: 0.0
 frcovmax: 0.1
 #Min and max of location and concentration of Von Mises distribution of lattice angle
 alocmin: 0.78
 alocmax: 2.36
 aconmin: 1.0
 aconmax: 2.0
 max_ele: 3
 # Required element
 req_ele: ['Li','Na', 'K']
 max_atom: 100
 # Penalty term of bond distance score
 vpen_min: 0.01
 vpen_max: 0.1
 vpen_minmax: 0.001
 # Reward function choice
 reward: reward_func_gd_dm_max_dist_SMACT